name: Publish to Maven Repo

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: macos-latest  # ← macOS damit iOS gebaut werden kann

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout maven-repo
        uses: actions/checkout@v4
        with:
          repository: devmre/maven-repo  # ← dein maven-repo
          path: ../maven-repo
          token: ${{ secrets.KmpNavigationToken }}

      - name: Publish
        run: ./gradlew publishAllPublicationsToGitHubMavenRepository

      - name: Push to maven-repo
        run: |
          cd ../maven-repo
          git config user.email "ci@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "release ${{ github.ref_name }}"
          git push