{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigation/1.3.0-alpha21/navigation-1.3.0-alpha21.module",
    "group": "com.github.devmre",
    "module": "navigation",
    "version": "1.3.0-alpha21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "navigation-desktop-1.3.0-alpha21.jar",
          "url": "navigation-desktop-1.3.0-alpha21.jar",
          "size": 89325,
          "sha512": "d4e14fb77bdaf4818519a840c452462e360fcf9b68d994612983a465db83a58eb50f4fe99492b2116141c64d863101c8dc5d3338973dbe06b305d6e0a8ff7d19",
          "sha256": "c2080efc063c4a9f8ab9427fab664ebe4951a460f2ffd3145e8b4adf5b4a07e6",
          "sha1": "87c9a2f37fbf06c4433717eea372782f889f8807",
          "md5": "77cbb46a2fc7d5237f56b1cd4bf3497d"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.8"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-desktop-1.3.0-alpha21.jar",
          "url": "navigation-desktop-1.3.0-alpha21.jar",
          "size": 89325,
          "sha512": "d4e14fb77bdaf4818519a840c452462e360fcf9b68d994612983a465db83a58eb50f4fe99492b2116141c64d863101c8dc5d3338973dbe06b305d6e0a8ff7d19",
          "sha256": "c2080efc063c4a9f8ab9427fab664ebe4951a460f2ffd3145e8b4adf5b4a07e6",
          "sha1": "87c9a2f37fbf06c4433717eea372782f889f8807",
          "md5": "77cbb46a2fc7d5237f56b1cd4bf3497d"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "navigation-desktop-1.3.0-alpha21-sources.jar",
          "url": "navigation-desktop-1.3.0-alpha21-sources.jar",
          "size": 18405,
          "sha512": "a97571987cd1a674ff1df2a587a03ae72a4990e56f0c4033e26d35cbfc42a4ea5f50284ce90f16714ee3955dbd8861392a4f9fd216ec2b4442b88059b72f9253",
          "sha256": "e132916579f65f7f9447931a84e3976fce156e5951cd6a4ddba64ae2f7169cf9",
          "sha1": "aaddbbcfbe4c4bf56c25f17b37d503430975a2ad",
          "md5": "0f30f6203c5019e39dbd83daf6893da4"
        }
      ]
    }
  ]
}
