{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigation/1.3.0-alpha16/navigation-1.3.0-alpha16.module",
    "group": "com.github.devmre",
    "module": "navigation",
    "version": "1.3.0-alpha16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.8"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-iosArm64Main-1.3.0-alpha16.klib",
          "url": "navigation-iosarm64-1.3.0-alpha16.klib",
          "size": 90795,
          "sha512": "d19dd195a705546352b0353f2aa4ed627827b30dbb3cb7a3e0bcff59556ebf5b23c2859b7935d698d289d923a3ba5bca3758f5a891ba9640448506253864ed1b",
          "sha256": "451207b64fe6e8394b88f333d041eefa3788c0acca3e3e26cf03b25797019e07",
          "sha1": "a06e94f3ed02c44f27279132a9ea4e18e8a35069",
          "md5": "8bce4954d1246b0570da49a2afd7d71e"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "navigation-iosarm64-1.3.0-alpha16-sources.jar",
          "url": "navigation-iosarm64-1.3.0-alpha16-sources.jar",
          "size": 18405,
          "sha512": "a97571987cd1a674ff1df2a587a03ae72a4990e56f0c4033e26d35cbfc42a4ea5f50284ce90f16714ee3955dbd8861392a4f9fd216ec2b4442b88059b72f9253",
          "sha256": "e132916579f65f7f9447931a84e3976fce156e5951cd6a4ddba64ae2f7169cf9",
          "sha1": "aaddbbcfbe4c4bf56c25f17b37d503430975a2ad",
          "md5": "0f30f6203c5019e39dbd83daf6893da4"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.8"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-1.3.0-alpha16.kotlin_resources.zip",
          "url": "navigation-iosarm64-1.3.0-alpha16-kotlin_resources.kotlin_resources.zip",
          "size": 344,
          "sha512": "89522ee14273d97982f009d23b9d66853cf833e7b6386fc02e266a371cd98174ab55c7bb1fce913d8504bc093a832141dab72ed4d2d57767bc1530c809552ddf",
          "sha256": "a8d22ffe89068148a28817a89888c1948b0d59d147de9441384726804644b0e5",
          "sha1": "94ebc146db9870a10b82d0509ff2166a71ad7806",
          "md5": "c0aa72d17578ec7693a0a2ada026be27"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.8"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-iosarm64-1.3.0-alpha16-metadata.jar",
          "url": "navigation-iosarm64-1.3.0-alpha16-metadata.jar",
          "size": 261,
          "sha512": "969e9e9445b00791c7aadbe308cf12b84dbb1f489617d67dc540fb5ca826d5846069681743a3c2f13ae6552382afdfd2638f7621a7bbbfa52dfaf863dd55b92b",
          "sha256": "c804a40263ed19dd2bf425eec8668919b407bc874f60d471398d242ca803ef41",
          "sha1": "0d7b31b436efad24195cd19b440f8386d5a333d5",
          "md5": "9aedd571e139144a551203a8e9482891"
        }
      ]
    }
  ]
}
